cinemaproject/cinemaapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'
urlpatterns = [
    path('',views.test,name='test'),
    path('movie/<int:film_id>/',views.detail,name='detail'),
    path('add/',views.addmovie,name='addmovie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
    ]

cinemaproject/cinemaproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('cinemaapp.urls')),
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
             document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

cinemaproject/cinemaapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name=models.CharField(max_length=200)
    des=models.TextField()
    year=models.IntegerField()
    image=models.ImageField(upload_to='images')

    def __str__(self):
        return self.name

cinemaproject/cinemaapp/forms.py
from django import forms
from .models import movie


class Movie_Form(forms.ModelForm):
    class Meta:
        model = movie
        fields = ['name', 'des', 'year', 'image']

cinemaproject/cinemaapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import movie
from.forms import Movie_Form
# Create your views here.
def test(request):
    movies=movie.objects.all()
    context={
        'movie_list':movies
    }
    return render(request,'index.html',context)
def detail(request,film_id):
    details=movie.objects.get(id=film_id)
    return render(request,'details.html',{'details':details})
def addmovie(request):
    if request.method=='POST':
        name=request.POST.get('name')
        des = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['image']
        add=movie(name=name,des=des,year=year,image=img)
        add.save()
    return render(request,'add.html')

def update(request,id):
    Mov=movie.objects.get(id=id)
    form=Movie_Form(request.POST or None,request.FILES,instance=Mov)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form_key':form,'Movie':Mov})

def delete(request,id):
    if request.method=='POST':
        mov=movie.objects.get(id=id)
        mov.delete()
        return redirect('/')
    return render(request,'delete.html')

cinemaproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter the movie name"><br>
    <input type="text" name="desc" placeholder="Enter the movie description"><br>
    <input type="number" name="year" placeholder="Enter the movie released year"><br>
    <input type="file" name="image"><br>
    <input type="submit">
</form>
{% endblock %}

cinemaproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movies</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
<!--    <img src="/docs/4.6/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">-->
    All About Movies
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

cinemaproject/templates/delete.html
<form method="post">
  {% csrf_token %}
  Are u sure to delete <input type="submit">
</form>

cinemaproject/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
           <img src="{{details.image.url}}" height="500" width="500">
        </div>
        <div class="col-md-6">
            <h3>{{details.name}}</h3>
            <h5>{{details.des}}</h5>
            <h6>Year-{{details.year}}</h6>
            <a class="btn btn-warning" href="{% url 'movieapp:update' details.id %}">Update here</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' details.id %}">Delete</a>
         </div>
    </div>
</div>
{% endblock %}

cinemaproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form_key.as_p}}
  <input type="submit">
</form>
{% endblock %}

cinemaproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}
         <div class="col-md-4">
        <div class="card" style="width: 18rem;">
  <img src="{{i.image.url}}" class="card-img-top" alt="..." width="100px" height="250px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.des}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">More details</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
    <br>
    <a class="btn btn-warning" href="{% url 'movieapp:addmovie' %}">Add more movies</a>
</div>
{% endblock %}